# "Planteamiento del problema"
""" La salud mental se ha consolidado como una de las principales preocupaciones de la salud publica a nivel mundial. La Organización Mundial de la Salud estima que los trastornos mentales generan pérdidas económicas globales cercanas al billón de dólares anuales por concepto de productividad no realizada, y advierte que aproximadamente el 15% de los trabajadores presenta algún trastorno  de este tipo. Dado que cerca del 60% de la población mundial desarrolla su actividad en un entorno laboral, la salud mental en el trabajo ha dejado de ser un asunto privado hasta el punto de que hoy ocupa un eje central tanto en las organizaciones como en las políticas públicas de empleo a nivel mundial. Desde una perspectiva más específica hacia el sector tecnológico los estudios disponibles documentan una prevalencia de malestar psicológico superior a las otras industrias, asociada a una cultura que normaliza las jornadas prolongadas.

Ahora bien, en este contexto el estigma da lugar a lo que la literatura denomina percepción de perjuicio profesional: la creencia de que divulgar una condición de salud mental tendrá consecuencias negativas en el desarrollo de la carrera.Desde una perspectiva más específica hacia el sector tecnológico los estudios disponibles documentan una prevalencia de malestar psicológico superior a las otras industrias, asociada a una cultura que normaliza las jornadas prolongadas, y con el avance exponencial de la tecnología en los últimos años la constante presión por innovar,  y la exigencia constante de actualización de habilidades. A ello se suma que una amplia mayoría de los empleados percibe estigma en su entorno laboral lo que constituye una barrera formidable para buscar ayuda y agrava el problema de fondo según Rado & Neagu, 2019; Sharma et al., 2018. Esta combinación de alta exigencia y estigma convierte al sector tecnológico en un caso especialmente relevante para el estudio de la salud mental. 

   Ahora bien, en este contexto el estigma da lugar a lo que la literatura denomina percepción de perjuicio profesional: la creencia de que divulgar una condición de salud mental tendrá consecuencias negativas en el desarrollo de la carrera, las oportunidades de ascenso o el estatus dentro de la organización. No obstante, persisten vacíos significativos sobre cómo esta percepción varía según el nivel jerárquico del puesto y el grupo de edad del trabajador. Respecto a la jerarquía, la teoría de demandas-control de Karasek (1979) sugiere que los puestos inferiores, con menor autonomía y control, deberían presentar mayor vulnerabilidad al estrés laboral. Sin embargo, no se ha examinado empíricamente si esa vulnerabilidad se traduce en una mayor percepción de perjuicio profesional por motivos de salud mental, ni si el nivel jerárquico modula esa percepción. 

 En cuanto a la edad, existen indicios de diferencias generacionales y de limitaciones de carrera asociadas a la edad en el sector tecnológico (CWJobs, 2019; Mental Health at Work Report, 2019), pero no se ha examinado si la percepción de perjuicio difiere entre grupos etarios ni cómo interactúa con la jerarquía. Por consiguiente, aunque se sabe que la salud mental es crítica en el sector tecnológico, no se ha establecido empíricamente si la percepción de perjuicio varía según la combinación de ambos factores. De ahí surge la siguiente pregunta: ¿Difiere la percepción de perjuicio profesional por motivos de salud mental según el nivel jerárquico y el grupo de edad en el sector tecnológico? Responderla permitirá identificar los segmentos más vulnerables y diseñar políticas basadas en evidencia. """

# "Objetivo general" 
"Determinar si la percepción de perjuicio profesional por motivos de salud mental difiere según el nivel jerárquico del puesto de trabajo y el grupo de edad del trabajador en el sector tecnológico. 

# "Objetivos específicos"
● "Caracterizar socio-demográficamente a la muestra de trabajadores del sector tecnológico (edad, género, nivel jerárquico y país). 
● "Describir la distribución de la percepción de perjuicio profesional por nivel jerárquico y grupo de edad. 
● "Analizar la relación entre la edad y la percepción de perjuicio dentro de cada nivel jerárquico. 
● "Determinar si existen diferencias significativas en la percepción de perjuicio según el nivel jerárquico y el grupo de edad, y si existe interacción entre ambos factores. "
